from scraper.config import LANG, COUNTRY

# Add more terms and rerun the python-scraper script to update the tables.
AGENT = {
    'en_us': ['boyfriend', 'girlfriend', 'wife', 'husband', 'spouse'],
    'en_in': ['boyfriend', 'girlfriend', 'wife', 'husband', 'spouse'],
    'en_bn': ['boyfriend', 'girlfriend', 'wife', 'husband', 'spouse'],
    'en_pk': ['boyfriend', 'girlfriend', 'wife', 'husband', 'spouse'],
    'en_gb': ['boyfriend', 'girlfriend', 'wife', 'husband', 'spouse'],
    'en_au': ['boyfriend', 'girlfriend', 'wife', 'husband', 'spouse'],
    'es_es': ['novio', 'novia', 'esposa', 'esposo', 'hombre', 'mujer'],
    'es_us': ['novio', 'novia', 'esposa', 'esposo', 'hombre', 'mujer'],
    'es_419': ['novio', 'novia', 'esposa', 'esposo', 'hombre', 'mujer'],
    'fr_fr': ['petit ami', 'petite amie', 'copain', 'copine', 'mari', 'femme', 'épouse', 'époux', 'conjoint'],
    'ru_ru': ['парень', 'подруга', 'жена', 'муж', 'супруг', 'муж'],
    'it_it': ['ragazzo', 'ragazza', 'fidanzato', 'fidanzata', 'moglie', 'marito', 'coniuge', 'marito'],
    'pt_br': ['namorado', 'namorada', 'esposa', 'marido', 'cônjuge', 'esposo', 'parceiro', 'parceira', 'mulher'],
    'pt_pt': ['namorado', 'namorada', 'esposa', 'marido', 'cônjuge', 'esposo', 'parceiro', 'parceira', 'mulher'],
    'ar_sa': ['حبيب' , 'حبيبة' , 'زوجة' , 'زوج' , 'شريك' , 'شريكة'],
    'ar_eg': ['حبيب' , 'حبيبة' , 'زوجة' , 'زوج' , 'شريك' , 'شريكة'],
    'ar_dz': ['حبيب' , 'حبيبة' , 'زوجة' , 'زوج' , 'شريك' , 'شريكة'],
    'bn_bn': ['প্রেমিক', 'প্রেমিকা', 'বন্ধু', 'বান্ধবী', 'স্ত্রী', 'স্বামী', 'পতি', 'পত্নী', 'বউ'],
    'ja_jp': ['彼氏','彼女','妻','夫','配偶者','夫'],
    'tr_tr': ['erkek arkadaş', 'kız arkadaş', 'eş', 'koca', 'eş', 'koca'],
    'ms_id': ['pacar', 'kekasih', 'istri', 'suami', 'pasangan', 'cewek', 'cowok', 'pelakor'],
    'de_de': ['Freund', 'Freundin', 'Ehefrau', 'Mann', 'Ehepartnerin', 'Ehepartner'],
    'vi': ['ban trai', 'ban gái', 'vợ', 'chồng', 'người đàn ông', 'người phụ nữ'],
}

PLAYSTORE_STARTING_QUERIES = {
    # English US
    'en_us': [
        'cheater', 'cheating',
        'cheating {agent}',
        'catch cheating',
        'catch cheating {agent}',
        'catch {agent} cheating',
        'track location', 'track {agent}', '{agent} tracker',
        'track kid', 'track children',
        'family tracker', 'child tracker',
        'track wife cheating', 'track {agent}\'s phone', 'track phone',
        'app for tracking location', 'track my phone',
        'find my phone', 'find my lost phone', 'find phone location',
        'call record',
        'listen to call',
        'gps tracking',
        'read emails from wife\'s phone',
        'spy my {agent}', 'app for spying',
        'apps for spying on my {agent}', 'spy on my {agent}',
        'track sms', 'sms tracker',
        'sync sms',
        'read sms from another phone',
        'message sync', 'phone control', 'control kids phone',
        'track email', 'track messages', 'track calls',
        'hidden keylogger', 'keylogger', 'keylogger for android',
        'phone sync',
    ],
    'en_pk': [
        'cheater', 'cheating',
        'cheating {agent}',
        'catch cheating',
        'catch cheating {agent}',
        'catch {agent} cheating',
        'track location', 'track {agent}', '{agent} tracker',
        'track kid', 'track children',
        'family tracker', 'child tracker',
        'track wife cheating', 'track {agent}\'s phone', 'track phone',
        'app for tracking location', 'track my phone',
        'find my phone', 'find my lost phone', 'find phone location',
        'call record',
        'listen to call',
        'gps tracking',
        'read emails from wife\'s phone',
        'spy my {agent}', 'app for spying',
        'apps for spying on my {agent}', 'spy on my {agent}',
        'track sms', 'sms tracker',
        'sync sms',
        'read sms from another phone',
        'message sync', 'phone control', 'control kids phone',
        'track email', 'track messages', 'track calls',
        'hidden keylogger', 'keylogger', 'keylogger for android',
        'phone sync',
    ],
    'en_in': [
        'cheater', 'cheating',
        'cheating {agent}',
        'catch cheating',
        'catch cheating {agent}',
        'catch {agent} cheating',
        'track location', 'track {agent}', '{agent} tracker',
        'track kid', 'track children',
        'family tracker', 'child tracker',
        'track wife cheating', 'track {agent}\'s phone', 'track phone',
        'app for tracking location', 'track my phone',
        'find my phone', 'find my lost phone', 'find phone location',
         'call record',
         'listen to call',
         'gps tracking',
         'read emails from wife\'s phone',
         'spy my {agent}', 'app for spying',
         'apps for spying on my {agent}', 'spy on my {agent}',
         'track sms', 'sms tracker',
         'sync sms',
         'read sms from another phone',
         'message sync', 'phone control', 'control kids phone',
         'track email', 'track messages', 'track calls',
         'hidden keylogger', 'keylogger', 'keylogger for android',
         'phone sync',
    ],
    'en_bn': [
         'cheater', 'cheating',
         'cheating {agent}',
         'catch cheating',
         'catch cheating {agent}',
         'catch {agent} cheating',
         'track location', 'track {agent}', '{agent} tracker',
         'track kid', 'track children',
         'family tracker', 'child tracker',
         'track wife cheating', 'track {agent}\'s phone', 'track phone',
         'app for tracking location', 'track my phone',
         'find my phone', 'find my lost phone', 'find phone location',
         'call record',
         'listen to call',
         'gps tracking',
         'read emails from wife\'s phone',
         'spy my {agent}', 'app for spying',
         'apps for spying on my {agent}', 'spy on my {agent}',
         'track sms', 'sms tracker',
         'sync sms',
         'read sms from another phone',
         'message sync', 'phone control', 'control kids phone',
         'track email', 'track messages', 'track calls',
         'hidden keylogger', 'keylogger', 'keylogger for android',
         'phone sync',
    ],
    # English UK
    'en_gb': [
        'cheater', 'cheating',
        'cheating {agent}',
        'catch cheating',
        'catch cheating {agent}',
        'catch {agent} cheating',
        'track location', 'track {agent}', '{agent} tracker',
        'track kid', 'track children',
        'family tracker', 'child tracker',
        'track wife cheating', 'track {agent}\'s phone', 'track phone',
        'app for tracking location', 'track my phone',
        'find my phone', 'find my lost phone', 'find phone location',
        'call record',
        'listen to call',
        'gps tracking',
        'read emails from wife\'s phone',
        'spy my {agent}', 'app for spying',
        'apps for spying on my {agent}', 'spy on my {agent}',
        'track sms', 'sms tracker',
        'sync sms',
        'read sms from another phone',
        'message sync', 'phone control', 'control kids phone',
        'track email', 'track messages', 'track calls',
        'hidden keylogger', 'keylogger', 'keylogger for android',
        'phone sync',
    ],
    # English Australia
    'en_au': [
        'cheater', 'cheating',
        'cheating {agent}',
        'catch cheating',
        'catch cheating {agent}',
        'catch {agent} cheating',
        'track location', 'track {agent}', '{agent} tracker',
        'track kid', 'track children',
        'family tracker', 'child tracker',
        'track wife cheating', 'track {agent}\'s phone', 'track phone',
        'app for tracking location', 'track my phone',
        'find my phone', 'find my lost phone', 'find phone location',
        'call record',
        'listen to call',
        'gps tracking',
        'read emails from wife\'s phone',
        'spy my {agent}', 'app for spying',
        'apps for spying on my {agent}', 'spy on my {agent}',
        'track sms', 'sms tracker',
        'sync sms',
        'read sms from another phone',
        'message sync', 'phone control', 'control kids phone',
        'track email', 'track messages', 'track calls',
        'hidden keylogger', 'keylogger', 'keylogger for android',
        'phone sync',
    ],
    # Spanish Spain
    'es_es': [
        'tramposo', 'tramposa', 'infiel', 'poniendo los cuernos', 'cuernos',
        'engañar', 'engañando','infidelidad',
        'atrapar a un tramposo', 'atrapar a una tramposa',
        'atrapar a un infiel', 'atrapar infieles', 'caza infieles',
        'atrapar {agent} infiel', 'descubrir a {agent} infiel',
        'rastrear ubicación', 'rastrear {agent}','hacer seguimiento a {agent}','rastreador de {agent}',
        'rastrear niño', 'rastrear niños',
        'localizador familiar', 'rastreador familiar','ubicación familiar','rastreador de niños',
        r'saber si {agent} te está engañando', r'rastrear (celular|teléfono) de mi {agent}',
        r'localizar (celular|teléfono)', r'localizar (celular|teléfono) perdido',
        'registro de llamadas', 'historial de llamadas',
        'escuchar llamadas',
        'rastreo gps', 'localizador gps',
        'leer el correo electrónico de mi {agent}','app para espiar',
        'apps para espiar mi {agent}',
        'rastrear sms', 'rastreador sms','localizador sms',
        'sincronizar mensajes', 'sincronizar sms',
        r'(leer|espiar) mensajes de texto desde otro (celular|teléfono)',
        'sincronización de SMS',
        'control telefónico',r'(manejar|controlar) un celular',r'(manejar|controlar) celular de niños',
        'rastrear correo electrónico','rastrear llamadas',
        'keylogger',' registrador de teclas', 'capturador de teclado','registrador de digitación', 'keylogger escondido', 'keylogger para android',
        r'sincronizar (celular|teléfono)',
    ],
    # Spanish US
    'es_us': [
        'tramposo', 'tramposa', 'infiel', 'poniendo los cuernos', 'cuernos',
        'engañar', 'engañando','infidelidad',
        'atrapar a un tramposo', 'atrapar a una tramposa',
        'atrapar a un infiel', 'atrapar infieles', 'caza infieles',
        'atrapar {agent} infiel', 'descubrir a {agent} infiel',
        'rastrear ubicación', 'rastrear {agent}','hacer seguimiento a {agent}','rastreador de {agent}',
        'rastrear niño', 'rastrear niños',
        'localizador familiar', 'rastreador familiar','ubicación familiar','rastreador de niños',
        r'saber si {agent} te está engañando', r'rastrear (celular|teléfono) de mi {agent}',
        r'localizar (celular|teléfono)', r'localizar (celular|teléfono) perdido',
        'registro de llamadas', 'historial de llamadas',
        'escuchar llamadas',
        'rastreo gps', 'localizador gps',
        'leer el correo electrónico de mi {agent}','app para espiar',
        'apps para espiar mi {agent}',
        'rastrear sms', 'rastreador sms','localizador sms',
        'sincronizar mensajes', 'sincronizar sms',
        r'(leer|espiar) mensajes de texto desde otro (celular|teléfono)',
        'sincronización de SMS',
        'control telefónico',r'(manejar|controlar) un celular',r'(manejar|controlar) celular de niños',
        'rastrear correo electrónico','rastrear llamadas',
        'keylogger',' registrador de teclas', 'capturador de teclado','registrador de digitación', 'keylogger escondido', 'keylogger para android',
        r'sincronizar (celular|teléfono)',
    ],
    # Spanish Latin America
    'es_419': [
        'tramposo', 'tramposa', 'infiel', 'poniendo los cuernos', 'cuernos',
        'engañar', 'engañando','infidelidad',
        'atrapar a un tramposo', 'atrapar a una tramposa',
        'atrapar a un infiel', 'atrapar infieles', 'caza infieles',
        'atrapar {agent} infiel', 'descubrir a {agent} infiel',
        'rastrear ubicación', 'rastrear {agent}','hacer seguimiento a {agent}','rastreador de {agent}',
        'rastrear niño', 'rastrear niños',
        'localizador familiar', 'rastreador familiar','ubicación familiar','rastreador de niños',
        r'saber si {agent} te está engañando', r'rastrear (celular|teléfono) de mi {agent}',
        r'localizar (celular|teléfono)', r'localizar (celular|teléfono) perdido',
        'registro de llamadas', 'historial de llamadas',
        'escuchar llamadas',
        'rastreo gps', 'localizador gps',
        'leer el correo electrónico de mi {agent}','app para espiar',
        'apps para espiar mi {agent}',
        'rastrear sms', 'rastreador sms','localizador sms',
        'sincronizar mensajes', 'sincronizar sms',
        r'(leer|espiar) mensajes de texto desde otro (celular|teléfono)',
        'sincronización de SMS',
        'control telefónico',r'(manejar|controlar) un celular',r'(manejar|controlar) celular de niños',
        'rastrear correo electrónico','rastrear llamadas',
        'keylogger',' registrador de teclas', 'capturador de teclado','registrador de digitación', 'keylogger escondido', 'keylogger para android',
        r'sincronizar (celular|teléfono)',
    ],
    # French France
    'fr_fr': [
        'mari volage', 'mari infidèle', 'femme volage', 'femme infidèle',
        r'{agent} (trompeur|trompeuse)',
        'découvrir infidélité'
        r'(attraper|surprendre) {agent} infidèle',
        'attraper {agent} infidèle',
        'suivre l’emplacement','suivre {agent}','traceur {agent}', 'traquer {agent}',
        'pister enfant', 'pister enfants',
        'traqueur familial ','localisateur familial',' traqueur enfant',
        'suivre femme infidèle','suivre téléphone de {agent}','localiser téléphone',
        'application pour suivre emplacement','suivre mon téléphone',
        'trouver mon téléphone','trouver mon téléphone perdu','trouver emplacement du téléphone',
        'enregistrement appel',
        'écouter pour appeler',
        'suivi gps',
        'lire les courriels du téléphone de ma femme',
        'espionner mon {agent} ','application pour espionnage',
        'des applications pour espionner mon {agent}','espionner mon {agent}',
        'suivre sms','suivi de sms','traçage sms',
        'sync sms',
        'lire sms depuis un autre téléphone',
        'synchronisation des messages','contrôle du téléphone', 'contrôle parental du téléphone des enfants',
        'suivre e-mails','suivre messages','suivre les appels',
        'keylogger caché','keylogger','enregistreur de frappe', 'keylogger pour android',
        'synchronisation du téléphone',
    ],
    # Russian Russia
    'ru_ru': [
        'супру́жеская изме́на', 'неверный',
        'неверный {agent}',
        'поймать неверность',
        'поймать неверных {agent}',
        'поймать {agent} обман',
        'отслеживать местоположение', 'отслеживать {agent}', 'трекер {agent}',
        'отследить ребенка', 'отследить детей',
        'семейный трекер', 'детский трекер',
        'отслеживать обман жены', 'отслеживать телефон {agent}', 'отслеживать телефон',
        'приложение для отслеживания местоположения', 'для отслеживания моего телефона',
        'найти мой телефон', 'найти мой потерянный телефон', 'найти местоположение телефона',
        'запись звонков',
        'слушать, чтобы позвонить',
        'Отслеживание GPS',
        'читать электронные письма с телефона жены',
        'шпионить за моим {agent}', 'приложением для шпионажа',
        'приложения для шпионажа в мой {agent}', 'для шпионажа в мой {agent}',
        'отслеживать смс', 'смс трекер',
        'синхронизировать смс',
        'читать смс с другого телефона',
        'Синхронизация сообщений', 'Управление телефоном', 'Управление детским телефоном',
        'отслеживать электронную почту', 'отслеживать сообщения', 'отслеживать звонки',
        'скрытый кейлоггер', 'кейлоггер', 'кейлоггер для Android',
        'Синхронизация телефона',
    ],
    # Italian Italy
    'it_it': [
        'infedele', 'tradire', 'tradimento',
        '{agent} infedele',
        'catturare infedeltà',
        'catturare {agent} infedele',
        'catturare {agent} che tradisce',
        'per tracciare la posizione', 'per tracciare {agent}', '{agent} tracker',
        'per tenere traccia dei bambini', 'per tracciare i bambini',
        'tracker familiare', 'tracker figlio',
        'per tracciare la moglie che tradisce', 'per tracciare il telefono {agent}', 'per tracciare il telefono',
        'app per localizzare la posizione', 'per localizzare il mio telefono',
        'per trovare il mio telefono', 'per trovare il mio telefono perso', 'per trovare la posizione del telefono',
        'registro delle chiamate',
        'ascoltare la chiamata',
        'tracciamento gps',
        'leggere le email dal telefono della moglie',
        'spiare il mio {agent}', 'app per spionaggio',
        'applicazioni per spiare il mio {agent}', 'spiare il mio {agent}',
        'per tracciare gli sms'
        'sincronizzare gli sms',
        'leggere gli sms da un altro telefono',
        'sincronizzazione messaggi', 'controllo telefono', 'per controllare il telefono dei bambini',
        'per tenere traccia delle email', 'per tracciare i messaggi', 'per tracciare le chiamate',
        'keylogger nascosto', 'keylogger', 'keylogger per Android'
        'sincronizzazione del telefono',
    ],
    # Portuguese Brazil
    'pt_br': [
         'traidor', 'infiel',
         'infiel {agent}',
         'descobrir  traição', 'descobrir se você está sendo traído'
         'descobrir {agent} infiel', 'descobrir traidor'
         'descobrir {agent} traindo',
         'rastrear localização', 'rastrear {agent}', '{agent} rastreador',
         'rastrear criança', 'rastrear crianças',
         'rastreador de família', 'rastreador de crianças',
         'rastrear a traição da esposa', 'rastrear o telefone do {agent}', 'rastrear o telefone',
         'aplicativos para rastrear localização', 'rastrear meu telefone', 'para rastrear meu telefone',
         'para encontrar meu telefone', 'para encontrar meu telefone perdido', 'para encontrar a localização do telefone',
         'registro de chamadas',
         'ouvir chamadas',
         'rastreamento por GPS',
         'ler e-mails do telefone da esposa',
         'espionar meu {agent}', 'aplicativo para espionagem',
         'aplicativos para espionar meu {agent}', 'para espionar meu {agent}',
         'para rastrear mensagens'
         'para sincronizar mensagens',
         'para ler mensagens de outro telefone',
         'sincronização de mensagens', 'para monitorar celular dos filhos',
         'rastrear e-mail', 'rastrear mensagens', 'rastrear chamadas',
         'keylogger oculto', 'keylogger', 'keylogger para android',
         'sincronização do telefone',
    ],
    # Portuguese Portugal
    'pt_pt': [
         'traidor', 'infiel',
         'infiel {agent}',
         'descobrir  traição', 'descobrir se você está sendo traído'
         'descobrir {agent} infiel', 'descobrir traidor'
         'descobrir {agent} traindo',
         'rastrear localização', 'rastrear {agent}', '{agent} rastreador',
         'rastrear criança', 'rastrear crianças',
         'rastreador de família', 'rastreador de crianças',
         'rastrear a traição da esposa', 'rastrear o telefone do {agent}', 'rastrear o telefone',
         'aplicativos para rastrear localização', 'rastrear meu telefone', 'para rastrear meu telefone',
         'para encontrar meu telefone', 'para encontrar meu telefone perdido', 'para encontrar a localização do telefone',
         'registro de chamadas',
         'ouvir chamadas',
         'rastreamento por GPS',
         'ler e-mails do telefone da esposa',
         'espionar meu {agent}', 'aplicativo para espionagem',
         'aplicativos para espionar meu {agent}', 'para espionar meu {agent}',
         'para rastrear mensagens'
         'para sincronizar mensagens',
         'para ler mensagens de outro telefone',
         'sincronização de mensagens', 'para monitorar celular dos filhos',
         'rastrear e-mail', 'rastrear mensagens', 'rastrear chamadas',
         'keylogger oculto', 'keylogger', 'keylogger para android',
         'sincronização do telefone',
    ],
    # Arabic
    'ar_sa': [
        'خائن' ,  'خائنة' ,   'الخائن' ,  'الخائنة' ,  'زوجي الخائن' ,  'زوجتي الخائنة' ,
        '{agent} خائن' ,  '{agent} خائنة' ,  'ال{agent} الخائن' ,  'ال{agent} الخائنة' ,
        'كشف الخيانة الزوجية' ,  'كشف الخيانة' ,  'كشف الخائن' ,  'كشف الخائنة' ,
        'كشف ال{agent} الخائن' ,  'كشف ال{agent} الخائنة' ,
        'كشف خيانة ال{agent}' ,
        'تتبع الموقع' ,  'تعقب الموقع' ,  'تتبع ال{agent}' ,   'تعقب ال{agent}' ,
        'تعقب الطفل' ,  'تعقب الأطفال' ,  'تتبع الأطفال' ,  'تعقب الاطفال' ,  'تتبع الاطفال'
        'تعقب الأسرة' ,  'تتبع الأسرة' ,  'تعقب الاسرة' ,  'تتبع الاسرة' ,  'تعقب العائلة' ,  'تتبع العائلة' ,  'تتبع الطفل' ,
        'تتبع الزوجة الخائنة' ,  'تعقب الزوجة الخائنة' ,  'تتبع الزوج الخائن' ,  'تعقب الزوج الخائن' ,  'تتبع هاتف ال{agent}' ,  'تعقب هاتف ال{agent}' ,  'تتبع جوال ال{agent}' ,  'تعقب جوال ال{agent}' ,  'تتبع الهاتف' ,  'تعقب الهاتف' ,   'تعقب الجوال' ,
        'تطبيق لتتبع الموقع' ,  'تطبيق لتعقب الموقع' ,  'برنامج لتعقب الموقع' ,  'برنامج لتتبع الموقع' ,   'تتبع هاتفي' ,   'تعقب هاتفي' ,  'تتبع جوالي' ,   'تعقب جوالي' ,
        'العثور على هاتفي' ,  'إيجاد هاتفي' ,  'العثور على هاتفي المفقود' ,  'إيجاد هاتفي المفقود' ,  'العثور على موقع الهاتف' ,  'إيجاد موقع الهاتف' ,
        'سجل المكالمات' ,  'سجل الاتصالات' ,
        'التنصت على المكالمات' ,   'التنصت على الاتصالات' ,
        'تتبع المواقع',  'تعقب المواقع',
        'قراءة بريد الزوجة الإلكتروني من هاتفها' ,
        'التجسس على ال{agent}' ,  'تطبيق للتجسس' ,  'برنامج للتجسس' ,  'تطبيق تجسس' ,  'برنامج تجسس' ,
        'تطبيقات للتجسس على ال{agent}' ,  'برامج للتجسس على ال{agent}' ,  'التجسس على {agent}ي' ,   'تطبيقات للتجسس على {agent}ي'  'التجسس على {agent}تي' ,   'تطبيقات للتجسس على {agent}تي' ,
        'تتبع الرسائل النصية' ,  'تعقب الرسائل النصية' ,
        'مزامنة الرسائل النصية' ,
        'قراءة الرسائل النصية من هاتف آخر' ,
        'مزامنة الرسائل' ,  'التحكم بالهاتف' ,  'التحكم بهاتف الطفل' ,  'التحكم بهواتف الأطفال' ,
        'تتبع البريد الإلكتروني' ,  'تعقب البريد الإلكتروني' ,  'تتبع الرسائل' ,  'تعقب الرسائل' ,  'تتبع المكالمات' ,  'تعقب المكالمات' ,  'تتبع الاتصالات' ,  'تعقب الاتصالات' ,
        'راصد لوحة مفاتيح خفي' ,  'راصد لوحة مفاتيح' ,  'راصد لوحة مفاتيح للأندرويد' ,
        'مزامنة الهاتف' ,  'مزامنة الهواتف' ,
    ],
    'ar_eg': [
        'خائن' ,  'خائنة' ,   'الخائن' ,  'الخائنة' ,  'زوجي الخائن' ,  'زوجتي الخائنة' ,
        '{agent} خائن' ,  '{agent} خائنة' ,  'ال{agent} الخائن' ,  'ال{agent} الخائنة' ,
        'كشف الخيانة الزوجية' ,  'كشف الخيانة' ,  'كشف الخائن' ,  'كشف الخائنة' ,
        'كشف ال{agent} الخائن' ,  'كشف ال{agent} الخائنة' ,
        'كشف خيانة ال{agent}' ,
        'تتبع الموقع' ,  'تعقب الموقع' ,  'تتبع ال{agent}' ,   'تعقب ال{agent}' ,
        'تعقب الطفل' ,  'تعقب الأطفال' ,  'تتبع الأطفال' ,  'تعقب الاطفال' ,  'تتبع الاطفال'
        'تعقب الأسرة' ,  'تتبع الأسرة' ,  'تعقب الاسرة' ,  'تتبع الاسرة' ,  'تعقب العائلة' ,  'تتبع العائلة' ,  'تتبع الطفل' ,
        'تتبع الزوجة الخائنة' ,  'تعقب الزوجة الخائنة' ,  'تتبع الزوج الخائن' ,  'تعقب الزوج الخائن' ,  'تتبع هاتف ال{agent}' ,  'تعقب هاتف ال{agent}' ,  'تتبع جوال ال{agent}' ,  'تعقب جوال ال{agent}' ,  'تتبع الهاتف' ,  'تعقب الهاتف' ,   'تعقب الجوال' ,
        'تطبيق لتتبع الموقع' ,  'تطبيق لتعقب الموقع' ,  'برنامج لتعقب الموقع' ,  'برنامج لتتبع الموقع' ,   'تتبع هاتفي' ,   'تعقب هاتفي' ,  'تتبع جوالي' ,   'تعقب جوالي' ,
        'العثور على هاتفي' ,  'إيجاد هاتفي' ,  'العثور على هاتفي المفقود' ,  'إيجاد هاتفي المفقود' ,  'العثور على موقع الهاتف' ,  'إيجاد موقع الهاتف' ,
        'سجل المكالمات' ,  'سجل الاتصالات' ,
        'التنصت على المكالمات' ,   'التنصت على الاتصالات' ,
        'تتبع المواقع',  'تعقب المواقع',
        'قراءة بريد الزوجة الإلكتروني من هاتفها' ,
        'التجسس على ال{agent}' ,  'تطبيق للتجسس' ,  'برنامج للتجسس' ,  'تطبيق تجسس' ,  'برنامج تجسس' ,
        'تطبيقات للتجسس على ال{agent}' ,  'برامج للتجسس على ال{agent}' ,  'التجسس على {agent}ي' ,   'تطبيقات للتجسس على {agent}ي'  'التجسس على {agent}تي' ,   'تطبيقات للتجسس على {agent}تي' ,
        'تتبع الرسائل النصية' ,  'تعقب الرسائل النصية' ,
        'مزامنة الرسائل النصية' ,
        'قراءة الرسائل النصية من هاتف آخر' ,
        'مزامنة الرسائل' ,  'التحكم بالهاتف' ,  'التحكم بهاتف الطفل' ,  'التحكم بهواتف الأطفال' ,
        'تتبع البريد الإلكتروني' ,  'تعقب البريد الإلكتروني' ,  'تتبع الرسائل' ,  'تعقب الرسائل' ,  'تتبع المكالمات' ,  'تعقب المكالمات' ,  'تتبع الاتصالات' ,  'تعقب الاتصالات' ,
        'راصد لوحة مفاتيح خفي' ,  'راصد لوحة مفاتيح' ,  'راصد لوحة مفاتيح للأندرويد' ,
        'مزامنة الهاتف' ,  'مزامنة الهواتف' ,
    ],
    'ar_dz': [
        'خائن' ,  'خائنة' ,   'الخائن' ,  'الخائنة' ,  'زوجي الخائن' ,  'زوجتي الخائنة' ,
        '{agent} خائن' ,  '{agent} خائنة' ,  'ال{agent} الخائن' ,  'ال{agent} الخائنة' ,
        'كشف الخيانة الزوجية' ,  'كشف الخيانة' ,  'كشف الخائن' ,  'كشف الخائنة' ,
        'كشف ال{agent} الخائن' ,  'كشف ال{agent} الخائنة' ,
        'كشف خيانة ال{agent}' ,
        'تتبع الموقع' ,  'تعقب الموقع' ,  'تتبع ال{agent}' ,   'تعقب ال{agent}' ,
        'تعقب الطفل' ,  'تعقب الأطفال' ,  'تتبع الأطفال' ,  'تعقب الاطفال' ,  'تتبع الاطفال'
        'تعقب الأسرة' ,  'تتبع الأسرة' ,  'تعقب الاسرة' ,  'تتبع الاسرة' ,  'تعقب العائلة' ,  'تتبع العائلة' ,  'تتبع الطفل' ,
        'تتبع الزوجة الخائنة' ,  'تعقب الزوجة الخائنة' ,  'تتبع الزوج الخائن' ,  'تعقب الزوج الخائن' ,  'تتبع هاتف ال{agent}' ,  'تعقب هاتف ال{agent}' ,  'تتبع جوال ال{agent}' ,  'تعقب جوال ال{agent}' ,  'تتبع الهاتف' ,  'تعقب الهاتف' ,   'تعقب الجوال' ,
        'تطبيق لتتبع الموقع' ,  'تطبيق لتعقب الموقع' ,  'برنامج لتعقب الموقع' ,  'برنامج لتتبع الموقع' ,   'تتبع هاتفي' ,   'تعقب هاتفي' ,  'تتبع جوالي' ,   'تعقب جوالي' ,
        'العثور على هاتفي' ,  'إيجاد هاتفي' ,  'العثور على هاتفي المفقود' ,  'إيجاد هاتفي المفقود' ,  'العثور على موقع الهاتف' ,  'إيجاد موقع الهاتف' ,
        'سجل المكالمات' ,  'سجل الاتصالات' ,
        'التنصت على المكالمات' ,   'التنصت على الاتصالات' ,
        'تتبع المواقع',  'تعقب المواقع',
        'قراءة بريد الزوجة الإلكتروني من هاتفها' ,
        'التجسس على ال{agent}' ,  'تطبيق للتجسس' ,  'برنامج للتجسس' ,  'تطبيق تجسس' ,  'برنامج تجسس' ,
        'تطبيقات للتجسس على ال{agent}' ,  'برامج للتجسس على ال{agent}' ,  'التجسس على {agent}ي' ,   'تطبيقات للتجسس على {agent}ي'  'التجسس على {agent}تي' ,   'تطبيقات للتجسس على {agent}تي' ,
        'تتبع الرسائل النصية' ,  'تعقب الرسائل النصية' ,
        'مزامنة الرسائل النصية' ,
        'قراءة الرسائل النصية من هاتف آخر' ,
        'مزامنة الرسائل' ,  'التحكم بالهاتف' ,  'التحكم بهاتف الطفل' ,  'التحكم بهواتف الأطفال' ,
        'تتبع البريد الإلكتروني' ,  'تعقب البريد الإلكتروني' ,  'تتبع الرسائل' ,  'تعقب الرسائل' ,  'تتبع المكالمات' ,  'تعقب المكالمات' ,  'تتبع الاتصالات' ,  'تعقب الاتصالات' ,
        'راصد لوحة مفاتيح خفي' ,  'راصد لوحة مفاتيح' ,  'راصد لوحة مفاتيح للأندرويد' ,
        'مزامنة الهاتف' ,  'مزامنة الهواتف' ,
    ],
    'bn_bn': [
        'প্রতারক', 'অসত', 'অবিশ্বস্ত', 'ঠগবাজ',
        'প্রতারক {agent}',
        'বিশ্বাসহীনতা ধরার app',
        'অবিশ্বস্ত {agent} ধরার app',
        '{agent}-এর  প্রতারণা ধরার app',
        'অবস্থান ট্র্যাক করা', '{agent} এর  লোকেশন ট্র্যাক করুন', '{agent} ট্র্যাকার',
        'বাচ্চা ট্র্যাক করার app', 'বাচ্চাদের লোকেশন ট্র্যাক করা',
        'পরিবার ট্র্যাকার', 'শিশু ট্র্যাকার',
        'ধগ স্ত্রীর অবস্থান ট্র্যাক করা', '{agent} এর ফোন ট্র্যাক করা', 'ফোন ট্র্যাক করতে',
        'অবস্থান ট্র্যাকিংএর অ্যাপ্লিকেশন', 'আমার ফোনটি ট্র্যাক করা',
        'আমার ফোন সন্ধান করার', 'আমার হারিয়ে যাওয়া ফোন খুঁজে পেতে', 'ফোনের অবস্থান সন্ধান করতে',
        'কল রেকর্ড করা',
        'অপরের কল শোনার app',
        'জিপিএস ট্র্যাকিং করার app', 'GPS ট্র্যাকিং করা'
        '{agent} এর ফোন থেকে ইমেল পড়া',
        'আমার {agent} এর ওপর নজরদারি করা', 'গুপ্তচরবৃত্তির জন্য অ্যাপ', 'নজরদারি কোরার app',
        'আমার {agent} এর ওপর স্পাই করা',
        'এসএমএস ট্র্যাক করার', 'এসএমএস ট্র্যাকার',
        'এসএমএস sync করা',
        'অন্য ফোন থেকে এসএমএস পড়া',
        'বাচ্চাদের ফোন নিয়ন্ত্রণ করার app', 'বার্তা sync করার app', 'অন্যের ফোন নিয়ন্ত্রণ করা',
        'ইমেল ট্র্যাক করতে', 'বার্তা ট্র্যাক করতে', 'কলগুলি ট্র্যাক করতে',
        'লুকানো কীলগার', 'keylogger', 'অ্যান্ড্রয়েডের জন্য কীলগার',
        'ফোন sync',
    ],
    'ja_jp': [
    '詐欺師','不誠実',
        '不誠実な{agent}',
        '不倫をキャッチするために',
        '不誠実な{agent}を捕まえる',
        '{agent}の不正行為をキャッチする',
        '場所を追跡する','{agent}を追跡する','{agent}トラッカー',
        '子供を追跡する','子供を追跡する',
        '家族トラッカー','子トラッカー',
        '妻の不正行為を追跡する','{agent} \の電話を追跡する','電話を追跡する',
        '位置を追跡するためのアプリ','私の電話を追跡する',
        '自分の電話を見つける','紛失した電話を見つける','電話の場所を見つける',
        '通話記録',
        '電話を聞く'
        'gps tracking',
        '{agent}の電話からメールを読む',
        '{agent}をスパイする','スパイするアプリ',
        '{agent}をスパイするアプリケーション','{agent}をスパイする',
        'SMSを追跡する','SMSトラッカー',
        'SMSを同期するには',
        '別の電話からSMSを読む',
        'メッセージ同期','電話制御','子供の電話を制御する',
        'メールを追跡する','メッセージを追跡する','通話を追跡する',
        '隠しキーロガー','キーロガー','アンドロイド用キーロガー',
        '電話同期',
    ],
    'tr_tr': [
        'aldatan', 'sadakatsiz',
        'sadakatsiz {agent}',
        'sadakatsizliği yakalamak',
        'sadakatsiz {agent} yakalamak,'
        '{agent} hile yakalamak',
        'konumu izlemek için', 'izlemek için {agent}', '{agent} izleyici',
        'çocuğu izlemek', 'çocukları izlemek',
        'aile izleyicisi', 'çocuk izleyicisi',
        'eş aldatmasını izlemek', '{agent} telefonunu izlemek', 'telefonu izlemek',
        'konum izleme uygulaması', 'telefonumu izlemek için',
        'telefonumu bulmak', 'kayıp telefonumu bulmak', 'telefon yerini bulmak',
        'çağrı kaydı',
        'aramayı dinlemek için',
        'GPS takibi',
        '{agent} adlı telefondan e-posta okumak için',
        '{agent} üzerinde casusluk yapmak', 'casusluk için uygulama',
        '{agent} casusluk için başvurular',' {agent} casusluk için ',
        'sms i izlemek', 'sms izci',
        'sms leri senkronize etmek',
        'sms i başka bir telefondan okumak için',
        'mesaj senkronizasyonu', 'telefon kontrolü', 'çocuk telefonunu kontrol etmek için',
        'e-postayı izlemek', 'mesajları izlemek', 'çağrıları izlemek',
        'gizli keylogger', 'keylogger', 'android için keylogger',
        'telefon senkronizasyonu',
    ],
    'ms_id': [
     'selingkuh', 'cheater', 'tidak setia',
      'tidak setia {agent}',
      'mencari tahu perselingkuhan',
      'mencari tahu perselingkungan {agent}'
      'melacak lokasi', 'mencari tahu lokasi',
      'melacak lokasi', 'mencari tahu lokasi', 'melacak {agent}', '{agent} pelacak',
      'melacak anak', 'melacak lokasi anak', 'melacak keberadaan anak',
      'pelacak keberadaan keluarga', 'pelacak keberadaan anak',
      'melacak {agent} selingkuh', 'melacak {agent}’s lokasi hp', 'melacak lokasi hp',
      'aplikasi melacak lokasi', 'melacak hp', 'melacak keberadaan hp', 'melacak pelakor',
      'menemukan hp hilang', 'mencari tahu keberadaan hp', 'mencari hp hilang',
      'catatan panggilan',
      'mendengar percakapan', 'menguping percakapan', 'menguping percakapan {agent}',
      'melacak gps',
    'membaca email pribadi {agent}', 'membaca email di hp {agent}', 'membaca email {agent}',
    'memata-matai {agent}', 'aplikasi untuk memata-matai', 'aplikasi untuk memata-matai {agent}', 'memata-matai {agent}', 'aplikasi mematai-matai',
    'melacak sms', 'pelacak sms',
    'menyinkronkan SMS',
    'membaca sms orang lain'
    'menyinkronkan sms', 'pengontrol hp',
    'mengontrol hp anak', 'melacak email', 'melacak pesan/sms', 'melacak panggilan telepon',
    'keylogger tersembunyi', 'keylogger',
    'keylogger android', 'menyinkronkan hp'
    ],
    # German Germany
    'de_de': [
        'Betrüger', 'Betrügerin', 'Betrug', 'cheating',
        '{agent} betrügen',
        'betrügende {agent}'
        'Betrug fangen',
        'Fang betrügerischen {agent}',
        'Fange betrügerische {agent}',
        'erwischen {agent} betrügen',
        'Ort verfolgen', 'track {agent}', '{agent} tracker', '{agent} verfolgen',
        'Kind verfolgen', 'Kinder verfolgen',
        'Familien-Tracker', 'Kinder-Tracker',
        'Track Frau betrügt', 'track {agent}\'s phone', 'Telefon verfolgen',
        'App zur Standortverfolgung', 'Verfolge mein Handy',
        'Finde mein Handy', 'finde mein verlorenes Telefon', 'Telefonstandort finden',
        'Anrufliste',
        'Hören Sie zu, um anzurufen',
        'GPS-Verfolgung', 'GPS tracking',
        'Lesen Sie E-Mails vom Telefon Ihrer Frau',
        'spioniere meinen {agent} aus', 'spioniere meine {agent} aus', 'App zum Spionieren',
        'Apps zum Ausspionieren meines {agent}', 'Apps zum Ausspionieren meiner {agent}', 'spioniere meinen {agent} aus', 'spioniere meine {agent} aus'
        'SMS verfolgen', 'SMS-Tracker',
        'SMS synchronisieren',
        'SMS von einem anderen Telefon lesen',
        'Nachrichtensynchronisierung', 'Telefonsteuerung', 'Kindertelefon steuern',
        'E-Mail verfolgen', 'Nachrichten verfolgen', 'Anrufe verfolgen',
        'versteckter Keylogger', 'Keylogger', 'Keylogger für Android',
        'Telefonsynchronisierung',
    ],
}

GOOGLE_STARTING_QUERY = {
    # English US
    'en_us': [
        "how to catch my cheating {agent} app",
        "how to track my cheating {agent} app",
        "app for spying on my {agent}",
        "app for tracking my {agent}",
        "get location of another phone app",
        "listen to calls from another device app",
        "track my {agent}",
        "track my {agent}s phone without them knowing",
        "track location of my {agent} app",
        "read sms from another phone app",
        "app for tracking my kids",
        "app for seeing my kids phone",
        "keylogger for android",
        "easy spy app for android",
        "hidden spy app for android",
        "app to see photos in my phone remotely",
        "see all whatsapp messages app",
        "see all facebook messages app",
        "spyware for android devices",
        "record calls app",
    ],
    'en_pk': [
        "how to catch my cheating {agent} app",
        "how to track my cheating {agent} app",
        "app for spying on my {agent}",
        "app for tracking my {agent}",
        "get location of another phone app",
        "listen to calls from another device app",
        "track my {agent}",
        "track my {agent}s phone without them knowing",
        "track location of my {agent} app",
        "read sms from another phone app",
        "app for tracking my kids",
        "app for seeing my kids phone",
        "keylogger for android",
        "easy spy app for android",
        "hidden spy app for android",
        "app to see photos in my phone remotely",
        "see all whatsapp messages app",
        "see all facebook messages app",
        "spyware for android devices",
        "record calls app",
    ],
    'en_in': [
        "how to catch my cheating {agent} app",
        "how to track my cheating {agent} app",
        "app for spying on my {agent}",
        "app for tracking my {agent}",
        "get location of another phone app",
        "listen to calls from another device app",
        "track my {agent}",
        "track my {agent}s phone without them knowing",
        "track location of my {agent} app",
        "read sms from another phone app",
        "app for tracking my kids",
        "app for seeing my kids phone",
        "keylogger for android",
        "easy spy app for android",
        "hidden spy app for android",
        "app to see photos in my phone remotely",
        "see all whatsapp messages app",
        "see all facebook messages app",
        "spyware for android devices",
        "record calls app",
    ],
    'en_bn': [
        "how to catch my cheating {agent} app",
        "how to track my cheating {agent} app",
        "app for spying on my {agent}",
        "app for tracking my {agent}",
        "get location of another phone app",
        "listen to calls from another device app",
        "track my {agent}",
        "track my {agent}s phone without them knowing",
        "track location of my {agent} app",
        "read sms from another phone app",
        "app for tracking my kids",
        "app for seeing my kids phone",
        "keylogger for android",
        "easy spy app for android",
        "hidden spy app for android",
        "app to see photos in my phone remotely",
        "see all whatsapp messages app",
        "see all facebook messages app",
        "spyware for android devices",
        "record calls app",
    ],
    # English UK
    'en_gb': [
        "how to catch my cheating {agent} app",
        "how to track my cheating {agent} app",
        "app for spying on my {agent}",
        "app for tracking my {agent}",
        "get location of another phone app",
        "listen to calls from another device app",
        "track my {agent}",
        "track my {agent}s phone without them knowing",
        "track location of my {agent} app",
        "read sms from another phone app",
        "app for tracking my kids",
        "app for seeing my kids phone",
        "keylogger for android",
        "easy spy app for android",
        "hidden spy app for android",
        "app to see photos in my phone remotely",
        "see all whatsapp messages app",
        "see all facebook messages app",
        "spyware for android devices",
        "record calls app",
    ],
    # English Australia
    'en_au': [
        "how to catch my cheating {agent} app",
        "how to track my cheating {agent} app",
        "app for spying on my {agent}",
        "app for tracking my {agent}",
        "get location of another phone app",
        "listen to calls from another device app",
        "track my {agent}",
        "track my {agent}s phone without them knowing",
        "track location of my {agent} app",
        "read sms from another phone app",
        "app for tracking my kids",
        "app for seeing my kids phone",
        "keylogger for android",
        "easy spy app for android",
        "hidden spy app for android",
        "app to see photos in my phone remotely",
        "see all whatsapp messages app",
        "see all facebook messages app",
        "spyware for android devices",
        "record calls app",
    ],
    # Spanish Spain
    'es_es': [
        "como atrapar a mi {agent} infiel app",
        "como rastrear mi {agent} infiel app",
        "app para espiar mi {agent}",
        "app para rastrear mi {agent}",
        r"obtener ubicación de otro (celular|teléfono) app",
        r"escuchar llamadas de otro (celular|teléfono) app",
        "rastrear mi {agent}','como saber donde esta mi {agent}",
        r"rastrear (celular|teléfono) de mi {agent} sin que (sepa|se de cuenta)",
        r"rastrear  ubicación de mi {agent} app",
        r"(leer|espiar) mensajes de texto de otro (celular|teléfono) app",
        r"(leer|espiar) sms de otro (celular|teléfono) app",
        "app para monitorear mis niños",
        "app para ver (celular|teléfono) de mis niños",
        "keylogger para android",
        "aplicación espía fácil para android",
        "app para espiar escondido para android",
        r"app para ver fotos de mi (celular|teléfono) remotamente",
        "ver todos mensajes de whatsapp app",
        "ver todos mensajes de facebook app",
        "spyware para dispositivo android",
        "grabar llamadas app",
    ],
    # Spanish US
    'es_us': [
        "como atrapar a mi {agent} infiel app",
        "como rastrear mi {agent} infiel app",
        "app para espiar mi {agent}",
        "app para rastrear mi {agent}",
        r"obtener ubicación de otro (celular|teléfono) app",
        r"escuchar llamadas de otro (celular|teléfono) app",
        "rastrear mi {agent}','como saber donde esta mi {agent}",
        r"rastrear (celular|teléfono) de mi {agent} sin que (sepa|se de cuenta)",
        r"rastrear  ubicación de mi {agent} app",
        r"(leer|espiar) mensajes de texto de otro (celular|teléfono) app",
        r"(leer|espiar) sms de otro (celular|teléfono) app",
        "app para monitorear mis niños",
        "app para ver (celular|teléfono) de mis niños",
        "keylogger para android",
        "aplicación espía fácil para android",
        "app para espiar escondido para android",
        r"app para ver fotos de mi (celular|teléfono) remotamente",
        "ver todos mensajes de whatsapp app",
        "ver todos mensajes de facebook app",
        "spyware para dispositivo android",
        "grabar llamadas app",
    ],
    # Spanish Latin America
    'es_419': [
        "como atrapar a mi {agent} infiel app",
        "como rastrear mi {agent} infiel app",
        "app para espiar mi {agent}",
        "app para rastrear mi {agent}",
        r"obtener ubicación de otro (celular|teléfono) app",
        r"escuchar llamadas de otro (celular|teléfono) app",
        "rastrear mi {agent}','como saber donde esta mi {agent}",
        r"rastrear (celular|teléfono) de mi {agent} sin que (sepa|se de cuenta)",
        r"rastrear  ubicación de mi {agent} app",
        r"(leer|espiar) mensajes de texto de otro (celular|teléfono) app",
        r"(leer|espiar) sms de otro (celular|teléfono) app",
        "app para monitorear mis niños",
        "app para ver (celular|teléfono) de mis niños",
        "keylogger para android",
        "aplicación espía fácil para android",
        "app para espiar escondido para android",
        r"app para ver fotos de mi (celular|teléfono) remotamente",
        "ver todos mensajes de whatsapp app",
        "ver todos mensajes de facebook app",
        "spyware para dispositivo android",
        "grabar llamadas app",
    ],
    'fr_fr': [
        r"comment (attraper|surprendre) {agent} infidèle",
        "comment suivre {agent} infidèle application",
        "application pour espionner {agent}",
        "application pour suivre {agent}",
        "obtenir l'emplacement d'un autre téléphone application",
        "écouter les appels depuis un autre appareil application", "application pour mettre un téléphone sur écoute",
        "suivre mon {agent}",
        "suivre le téléphone de mon {agent} à son insu",
        "suivre l'emplacement de {agent} application",
        "lire des sms depuis un autre téléphone application",
        "application pour suivre mes enfants",
        "app pour voir téléphone de mes enfants",
        "keylogger pour android", "enregistreur de frappe pour Android",
        "application d'espionnage facile pour Android",
        "application d'espionnage cachée pour Android",
        "application pour voir des photos dans mon téléphone à distance",
        "voir tous les messages WhatsApp app",
        "voir tous les messages facebook app",
        "spyware pour les appareils Android",
        "enregistrer les appels app",
    ],
    'ru_ru': [
        "как поймать моего неверного {agent}; приложение",
        "как отследить мое неверное {agent}; приложение",
        "приложение, чтобы шпионить за моим {agent}",
        "приложение для отслеживания моего {agent}",
        "приложение для определения местоположения другого телефона",
        "приложение для прослушивания вызовов с другого устройства",
        "отслеживать мой {agent}",
        "отслеживать телефон моего {agent} без их ведома",
        "приложение для отслеживания местоположения моего {agent}",
        "приложение для чтения смс с другого телефона",
        "приложение для отслеживания моих детей",
        "приложение для просмотра телефона моих детей",
        "Кейлоггер для Android",
        "Легкое шпионское приложение для Android",
        "шпионское приложение для Android",
        "приложение для удаленного просмотра фотографий в моем телефоне",
        "приложение, чтобы увидеть все сообщения WhatsApp",
        "приложение, чтобы увидеть все сообщения Facebook",
        "шпионское ПО для устройств Android",
        "приложение для записи звонков",
    ],
    'it_it': [
        "come scoprire se il {agent} ti tradisce, app, applicazione",
        "come tenere localizzazione del mio {agent} infedele, app, applicazione",
        "app, applicazione per spiare il mio {agent}",
        "app, applicazione per localizzare il mio {agent}",
        "app, applicazione per ottenere la posizione di un altro telefono",
        "app, applicazione per ascoltare le chiamate da un altro dispositivo",
        "localizzare il mio {agent}",
        "localizzare il telefono del mio {agent} senza che lo sappiano",
        "app, applicazione per localizzare la posizione del mio {agent}",
        "app, applicazione per leggere sms da un altro telefono",
        "app, applicazione per localizzare i miei figli",
        "app, applicazione per vedere il telefono dei miei figli",
        "keylogger per Android",
        "app spia facile per Android",
        "app spia nascosta per Android",
        "app, applicazione per vedere le foto sul mio telefono da remoto",
        "app, applicazione per vedere tutti i messaggi di whatsapp",
        "app, applicazione per vedere tutti i messaggi di Facebook",
        "spyware per dispositivi Android",
        "app, applicazione per registrare le chiamate",
    ],
    # Portuguese Brazil
    'pt_br': [
         "como descobrir meu {agent} infiel; aplicativo",
         "como rastrear meu {agent} infiel; aplicação, aplicação",
         "app, aplicativo para espionar meu {agent}",
         "app, aplicativo para rastrear meu {agent}",
         "app, aplicativo para encontrar a localização de outro telefone",
         "app, aplicativo para ouvir chamadas de outro dispositivo",
         "rastrear meu {agent}",
         "rastrear o telefone do meu {agent} sem que eles saibam","rastrear o telefone da minha {agent} sem que ela saiba"
         "app, aplicativo para rastrear a localização do meu {agent}",
         "app, aplicativo para ler sms de outro telefone",
         "app, aplicativo para rastrear meus filhos",
         "app, aplicativo para ver o telefone dos meus filhos",
         "keylogger for android",
         "app, aplicativo espiao fácil para android",
         "app, aplicativo espiao oculto para android",
         "app, aplicativo para ver fotos no meu telefone remotamente",
         "app, aplicativo para ver todas as mensagens do whatsapp",
         "app, aplicativo para ver todas as mensagens do facebook",
         "software espiao para dispositivos Android", "programa espiao para dispositivos Android",
         "app, aplicativo para gravar ligação",
    ],
    # Portuguese Portugal
    'pt_pt': [
         "como descobrir meu {agent} infiel; aplicativo",
         "como rastrear meu {agent} infiel; aplicação, aplicação",
         "app, aplicativo para espionar meu {agent}",
         "app, aplicativo para rastrear meu {agent}",
         "app, aplicativo para encontrar a localização de outro telefone",
         "app, aplicativo para ouvir chamadas de outro dispositivo",
         "rastrear meu {agent}",
         "rastrear o telefone do meu {agent} sem que eles saibam","rastrear o telefone da minha {agent} sem que ela saiba"
         "app, aplicativo para rastrear a localização do meu {agent}",
         "app, aplicativo para ler sms de outro telefone",
         "app, aplicativo para rastrear meus filhos",
         "app, aplicativo para ver o telefone dos meus filhos",
         "keylogger for android",
         "app, aplicativo espiao fácil para android",
         "app, aplicativo espiao oculto para android",
         "app, aplicativo para ver fotos no meu telefone remotamente",
         "app, aplicativo para ver todas as mensagens do whatsapp",
         "app, aplicativo para ver todas as mensagens do facebook",
         "software espiao para dispositivos Android", "programa espiao para dispositivos Android",
         "app, aplicativo para gravar ligação",
    ],
    'ar_sa': [
        "كيفية كشف {agent}ي الخائن ؛ تطبيق ,  برنامج" ,  "كيفية كشف {agent}تي الخائنة ؛ تطبيق ,  برنامج" ,  "كيفية كشف ال{agent} الخائن ؛ تطبيق ,  برنامج" ,  "كيفية كشف ال{agent} الخائنة ؛ تطبيق ,  برنامج" ,
       "كيفية تتبع {agent}ي الخائن؛ تطبيق ,  برنامج" ,  "كيفية تعقب ال{agent} الخائن؛ تطبيق ,  برنامج" ,  "كيفية تتبع {agent}تي الخائنة؛ تطبيق ,  برنامج" ,  "كيفية تعقب ال{agent} الخائنة؛ تطبيق ,  برنامج"
       "برنامج ,  تطبيق للتجسس على {agent}" ,  "برنامج ,  تطبيق للتجسس على ال{agent}" ,  "برنامج ,  تطبيق للتجسس على {agent}ي" ,  "برنامج ,  تطبيق للتجسس على {agent}تي" ,
       "برنامج ,  تطبيق لتتبع ال{agent}" ,  "برنامج ,  تطبيق لتتبع ال{agent}" ,   "برنامج ,  تطبيق لتتبع {agent}تي" ,  "برنامج ,  تطبيق لتتبع {agent}ي" ,
       "برنامج ,  تطبيق للحصول على موقع هاتف آخر" ,
       "برنامج ,  تطبيق للتنصت على مكالمات جهاز آخر" ,  "برنامج ,  تطبيق للتنصت على مكالمات أجهزة أخرى" ,  "برنامج ,  تطبيق للتنصت على اتصالات جهاز آخر" ,  "برنامج ,  تطبيق للتنصت على اتصالات أجهزة أخرى" ,
       "تتبع {agent}" ,  "تعقب {agent}" ,  "تتبع ال{agent}" ,  "تعقب ال{agent}" ,
       "تتبع هاتف {agent} دون علمه" ,   "تعقب هاتف {agent} دون علمه" ,  "تتبع هاتف ال{agent} دون علمه" ,   "تعقب هاتف ال{agent} دون علمه" ,  "تتبع هاتف {agent}ي دون علمه" ,   "تعقب هاتف {agent}ي دون علمه" ,  "تتبع هاتف {agent}تي دون علمها" ,   "تعقب هاتف {agent}تي دون علمها" ,
       "برنامج ,  تطبيق لتتبع موقع ال{agent}" ,  "برنامج ,  تطبيق لتعقب موقع ال{agent}" ,   "برنامج ,  تطبيق لتتبع موقع {agent}ي" ,  "برنامج ,  تطبيق لتعقب موقع {agent}ي" ,  "برنامج ,  تطبيق لتتبع موقع {agent}تي" ,  "برنامج ,  تطبيق لتعقب موقع {agent}تي" ,
       "برنامج ,  تطبيق لقراءة الرسائل النصية من هاتف آخر" ,
       "برنامج ,  تطبيق لتتبع أطفالي" ,  "برنامج ,  تطبيق لتعقب أطفالي" ,   "برنامج ,  تطبيق لتتبع أبنائي" ,  "برنامج ,  تطبيق لتعقب أبنائي" ,
       "برنامج ,  تطبيق لرؤية هواتف أطفالي" ,  "برنامج ,  تطبيق لرؤية هاتف طفلي" ,  "برنامج ,  تطبيق لرؤية هاتف ابني" ,  "برنامج ,  تطبيق لرؤية هواتف أبنائي"
       "راصد لوحة مفاتيح للأندرويد" ,
       "تطبيق تجسس سهل للأندرويد" ,  "برنامج تجسس سهل للأندرويد" ,
       "تطبيق تجسس مخفي للأندرويد" ,  "برنامج تجسس مخفي للأندرويد" ,
       "برنامج ,  تطبيق لرؤية الصور من هاتفي عن بعد" ,
       "برنامج ,  تطبيق لرؤية جميع رسائل واتساب" ,  "برنامج ,  تطبيق لرؤية جميع رسائل الواتساب" ,
       "برنامج ,  تطبيق لرؤية جميع رسائل فيسبوك" ,   "برنامج ,  تطبيق لرؤية جميع رسائل الفيسبوك" ,  "برنامج ,  تطبيق لرؤية جميع رسائل الفيس بوك" ,  "برنامج ,  تطبيق لرؤية جميع رسائل فيس بوك" ,
       "برامج تجسس للأندرويد" ,
       "برنامج ,  تطبيق لتسجيل المكالمات" ,   "برنامج ,  تطبيق لتسجيل الاتصالات" ,
     ],
    'ar_eg': [
        "كيفية كشف {agent}ي الخائن ؛ تطبيق ,  برنامج" ,  "كيفية كشف {agent}تي الخائنة ؛ تطبيق ,  برنامج" ,  "كيفية كشف ال{agent} الخائن ؛ تطبيق ,  برنامج" ,  "كيفية كشف ال{agent} الخائنة ؛ تطبيق ,  برنامج" ,
       "كيفية تتبع {agent}ي الخائن؛ تطبيق ,  برنامج" ,  "كيفية تعقب ال{agent} الخائن؛ تطبيق ,  برنامج" ,  "كيفية تتبع {agent}تي الخائنة؛ تطبيق ,  برنامج" ,  "كيفية تعقب ال{agent} الخائنة؛ تطبيق ,  برنامج"
       "برنامج ,  تطبيق للتجسس على {agent}" ,  "برنامج ,  تطبيق للتجسس على ال{agent}" ,  "برنامج ,  تطبيق للتجسس على {agent}ي" ,  "برنامج ,  تطبيق للتجسس على {agent}تي" ,
       "برنامج ,  تطبيق لتتبع ال{agent}" ,  "برنامج ,  تطبيق لتتبع ال{agent}" ,   "برنامج ,  تطبيق لتتبع {agent}تي" ,  "برنامج ,  تطبيق لتتبع {agent}ي" ,
       "برنامج ,  تطبيق للحصول على موقع هاتف آخر" ,
       "برنامج ,  تطبيق للتنصت على مكالمات جهاز آخر" ,  "برنامج ,  تطبيق للتنصت على مكالمات أجهزة أخرى" ,  "برنامج ,  تطبيق للتنصت على اتصالات جهاز آخر" ,  "برنامج ,  تطبيق للتنصت على اتصالات أجهزة أخرى" ,
       "تتبع {agent}" ,  "تعقب {agent}" ,  "تتبع ال{agent}" ,  "تعقب ال{agent}" ,
       "تتبع هاتف {agent} دون علمه" ,   "تعقب هاتف {agent} دون علمه" ,  "تتبع هاتف ال{agent} دون علمه" ,   "تعقب هاتف ال{agent} دون علمه" ,  "تتبع هاتف {agent}ي دون علمه" ,   "تعقب هاتف {agent}ي دون علمه" ,  "تتبع هاتف {agent}تي دون علمها" ,   "تعقب هاتف {agent}تي دون علمها" ,
       "برنامج ,  تطبيق لتتبع موقع ال{agent}" ,  "برنامج ,  تطبيق لتعقب موقع ال{agent}" ,   "برنامج ,  تطبيق لتتبع موقع {agent}ي" ,  "برنامج ,  تطبيق لتعقب موقع {agent}ي" ,  "برنامج ,  تطبيق لتتبع موقع {agent}تي" ,  "برنامج ,  تطبيق لتعقب موقع {agent}تي" ,
       "برنامج ,  تطبيق لقراءة الرسائل النصية من هاتف آخر" ,
       "برنامج ,  تطبيق لتتبع أطفالي" ,  "برنامج ,  تطبيق لتعقب أطفالي" ,   "برنامج ,  تطبيق لتتبع أبنائي" ,  "برنامج ,  تطبيق لتعقب أبنائي" ,
       "برنامج ,  تطبيق لرؤية هواتف أطفالي" ,  "برنامج ,  تطبيق لرؤية هاتف طفلي" ,  "برنامج ,  تطبيق لرؤية هاتف ابني" ,  "برنامج ,  تطبيق لرؤية هواتف أبنائي"
       "راصد لوحة مفاتيح للأندرويد" ,
       "تطبيق تجسس سهل للأندرويد" ,  "برنامج تجسس سهل للأندرويد" ,
       "تطبيق تجسس مخفي للأندرويد" ,  "برنامج تجسس مخفي للأندرويد" ,
       "برنامج ,  تطبيق لرؤية الصور من هاتفي عن بعد" ,
       "برنامج ,  تطبيق لرؤية جميع رسائل واتساب" ,  "برنامج ,  تطبيق لرؤية جميع رسائل الواتساب" ,
       "برنامج ,  تطبيق لرؤية جميع رسائل فيسبوك" ,   "برنامج ,  تطبيق لرؤية جميع رسائل الفيسبوك" ,  "برنامج ,  تطبيق لرؤية جميع رسائل الفيس بوك" ,  "برنامج ,  تطبيق لرؤية جميع رسائل فيس بوك" ,
       "برامج تجسس للأندرويد" ,
       "برنامج ,  تطبيق لتسجيل المكالمات" ,   "برنامج ,  تطبيق لتسجيل الاتصالات" ,
     ],
    'ar_dz': [
            "كيفية كشف {agent}ي الخائن ؛ تطبيق ,  برنامج" ,  "كيفية كشف {agent}تي الخائنة ؛ تطبيق ,  برنامج" ,  "كيفية كشف ال{agent} الخائن ؛ تطبيق ,  برنامج" ,  "كيفية كشف ال{agent} الخائنة ؛ تطبيق ,  برنامج" ,
           "كيفية تتبع {agent}ي الخائن؛ تطبيق ,  برنامج" ,  "كيفية تعقب ال{agent} الخائن؛ تطبيق ,  برنامج" ,  "كيفية تتبع {agent}تي الخائنة؛ تطبيق ,  برنامج" ,  "كيفية تعقب ال{agent} الخائنة؛ تطبيق ,  برنامج"
           "برنامج ,  تطبيق للتجسس على {agent}" ,  "برنامج ,  تطبيق للتجسس على ال{agent}" ,  "برنامج ,  تطبيق للتجسس على {agent}ي" ,  "برنامج ,  تطبيق للتجسس على {agent}تي" ,
           "برنامج ,  تطبيق لتتبع ال{agent}" ,  "برنامج ,  تطبيق لتتبع ال{agent}" ,   "برنامج ,  تطبيق لتتبع {agent}تي" ,  "برنامج ,  تطبيق لتتبع {agent}ي" ,
           "برنامج ,  تطبيق للحصول على موقع هاتف آخر" ,
           "برنامج ,  تطبيق للتنصت على مكالمات جهاز آخر" ,  "برنامج ,  تطبيق للتنصت على مكالمات أجهزة أخرى" ,  "برنامج ,  تطبيق للتنصت على اتصالات جهاز آخر" ,  "برنامج ,  تطبيق للتنصت على اتصالات أجهزة أخرى" ,
           "تتبع {agent}" ,  "تعقب {agent}" ,  "تتبع ال{agent}" ,  "تعقب ال{agent}" ,
           "تتبع هاتف {agent} دون علمه" ,   "تعقب هاتف {agent} دون علمه" ,  "تتبع هاتف ال{agent} دون علمه" ,   "تعقب هاتف ال{agent} دون علمه" ,  "تتبع هاتف {agent}ي دون علمه" ,   "تعقب هاتف {agent}ي دون علمه" ,  "تتبع هاتف {agent}تي دون علمها" ,   "تعقب هاتف {agent}تي دون علمها" ,
           "برنامج ,  تطبيق لتتبع موقع ال{agent}" ,  "برنامج ,  تطبيق لتعقب موقع ال{agent}" ,   "برنامج ,  تطبيق لتتبع موقع {agent}ي" ,  "برنامج ,  تطبيق لتعقب موقع {agent}ي" ,  "برنامج ,  تطبيق لتتبع موقع {agent}تي" ,  "برنامج ,  تطبيق لتعقب موقع {agent}تي" ,
           "برنامج ,  تطبيق لقراءة الرسائل النصية من هاتف آخر" ,
           "برنامج ,  تطبيق لتتبع أطفالي" ,  "برنامج ,  تطبيق لتعقب أطفالي" ,   "برنامج ,  تطبيق لتتبع أبنائي" ,  "برنامج ,  تطبيق لتعقب أبنائي" ,
           "برنامج ,  تطبيق لرؤية هواتف أطفالي" ,  "برنامج ,  تطبيق لرؤية هاتف طفلي" ,  "برنامج ,  تطبيق لرؤية هاتف ابني" ,  "برنامج ,  تطبيق لرؤية هواتف أبنائي"
           "راصد لوحة مفاتيح للأندرويد" ,
           "تطبيق تجسس سهل للأندرويد" ,  "برنامج تجسس سهل للأندرويد" ,
           "تطبيق تجسس مخفي للأندرويد" ,  "برنامج تجسس مخفي للأندرويد" ,
           "برنامج ,  تطبيق لرؤية الصور من هاتفي عن بعد" ,
           "برنامج ,  تطبيق لرؤية جميع رسائل واتساب" ,  "برنامج ,  تطبيق لرؤية جميع رسائل الواتساب" ,
           "برنامج ,  تطبيق لرؤية جميع رسائل فيسبوك" ,   "برنامج ,  تطبيق لرؤية جميع رسائل الفيسبوك" ,  "برنامج ,  تطبيق لرؤية جميع رسائل الفيس بوك" ,  "برنامج ,  تطبيق لرؤية جميع رسائل فيس بوك" ,
           "برامج تجسس للأندرويد" ,
           "برنامج ,  تطبيق لتسجيل المكالمات" ,   "برنامج ,  تطبيق لتسجيل الاتصالات" ,
    ],
    'bn_bn': [
       "কীভাবে আমার অবিশ্বস্ত {agent}কে ধরবো; অ্যাপ, অ্যাপ্লিকেশন",
       "কীভাবে আমার প্রতারক {agent}কে  ট্র্যাক করব; অ্যাপ, অ্যাপ্লিকেশন",
       "আমার {agent} এর ওপর নজরদারি করার app, আপ্লিকেশন",
       "আমার {agent} কে ট্র্যাক করার app, আপ্লিকেশন",
       "অন্যের ফোনের অবস্থান পাওয়ার জন্য অ্যাপ্লিকেশন",
       "অন্য ডিভাইস থেকে কল শুনার অ্যাপ্লিকেশন",
       "আমার {agent} ট্র্যাক করা ",
       "আমার {agent}কে না জানিয়ে তার ফোন ট্র্যাক করা",
       "আমার {এজেন্ট}এর ফোন তার অজান্তে ট্র্যাক করা",
       "আমার {agent}এর  location, অবস্থান ট্র্যাক করার অ্যাপ্লিকেশন,"
       "অন্য ফোন থেকে এসএমএস পড়ার অ্যাপ্লিকেশন",
       "আমার বাচ্চাদের সন্ধানের জন্য অ্যাপ্লিকেশন",
       "আমার বাচ্চাদের ফোন নজর রাখার অ্যাপ্লিকেশন",
       "অ্যান্ড্রয়েডের জন্য keylogger",
       "অ্যান্ড্রয়েডের জন্য সহজ গুপ্তচর অ্যাপ্লিকেশন",
       "অ্যান্ড্রয়েডের জন্য গোপন গুপ্তচর অ্যাপ্লিকেশন",
       "আমার ফোনে দূর থেকে ফটো দেখার অ্যাপ্লিকেশন",
       "সমস্ত হোয়াটসঅ্যাপ বার্তা দেখার অ্যাপ্লিকেশন",
       "সমস্ত ফেসবুক বার্তা দেখার অ্যাপ্লিকেশন",
       "অ্যান্ড্রয়েড ডিভাইসের জন্য স্পাইওয়্যার",
       "কল রেকর্ড করার অ্যাপ্লিকেশন",
    ],
    'tr_tr': [
       "sadakatsiz {agent}; uygulama, uygulama nasıl yakalanır",
       "sadakatsiz {agent}; uygulamam, başvurum nasıl izlenir",
       "uygulama, {agent} üzerinde casusluk için başvuru",
       "uygulama, {agent} izleme uygulaması",
       "uygulama, başka bir telefonun yerini almak için uygulama",
       "uygulama, başka bir cihazdan gelen aramaları dinlemek için uygulama",
       "{agent} takip et",
       "bilmeden {agent} telefonumu takip et",
       "uygulama, {agent} konumumu izleme uygulaması",
       "uygulama, başka bir telefondan sms okumak için uygulama",
       "uygulama, çocuklarımı izlemek için başvuru",
       "app, benim çocuklar telefon görmek için başvuru",
       "android için keylogger",
       "android için kolay casus uygulaması",
       "android için gizli casus uygulaması",
       "uygulama, fotoğrafları telefonumda uzaktan görme uygulaması",
       "app, tüm whatsapp mesajlarını görmek için uygulama",
       "uygulama, tüm facebook mesajlarını görmek için uygulama",
       "android cihazlar için casus yazılım",
       "uygulama, çağrıları kaydetmek için uygulama",
    ],
    'ja_jp': [
       "不誠実な{agent};アプリ,アプリケーションをキャッチする方法",
       "不実な{agent};アプリ,アプリケーションを追跡する方法",
       "アプリ,{エージェント}をスパイするためのアプリケーション",
       "アプリ,{エージェント}を追跡するためのアプリケーション",
       "アプリ,別の電話の位置を取得するアプリケーション",
       "アプリ,別のデバイスからの呼び出しをリッスンするアプリケーション",
       "{エージェント}を追跡",
       "{エージェント}の電話を,彼らが知らないうちに追跡する",
       "アプリ,{エージェント}の位置を追跡するアプリケーション",
       "アプリ,別の電話からSMSを読むためのアプリケーション",
       "アプリ,私の子供を追跡するためのアプリケーション",
       "アプリ,私の子供の電話を見るためのアプリケーション",
       "アンドロイド用キーロガー",
       "Android用の簡単なスパイアプリ",
       "アンドロイド用隠しスパイアプリ",
       "アプリ,スマートフォンで写真をリモートで見るためのアプリケーション",
       "アプリ,すべてのwhatsappメッセージを表示するアプリケーション",
       "アプリ,すべてのFacebookメッセージを表示するアプリケーション",
       "Androidデバイス用のスパイウェア",
       "アプリ,通話を録音するアプリケーション",
    ],
    'ms_id': [
        "menangkap {agent} selingkuh; app, aplikasi", "menangkap perselingkuhan; app aplikasi",
        "cara melacak {agent} selingkuh; app, aplikasi", "cara melacak {agent} tidak setia; app, aplikasi",
        "app, aplikasi untuk melacak {agent}",
        "app, aplikasi untuk mata-matai {agent}",
        "app, aplikasi melacak lokasi hp lain",
        "app, aplikasi menguping percakapan telepon lain",
        "lacak {agent} saya",
        "lacak hp {agent} diam diam",
        "aplikasi melacak lokasi {agent}", "aplikasi mlelacak lokasi pasangan",
        "app, aplikasi untuk membaca sms dari hp lain",
        "app, aplikasi untuk melacak anak",
       "app, aplikasi untuk mengakses hp anak",
       "keylogger untuk android",
       "aplikasi muda untuk mata-matai",
       "aplikasi tersembuni untuk mata-matai",
       "app, aplikasi untuk mengakses photo di hp organ lain",
       "app, aplikasi untuk membaca whatsapp, sms", "app, aplikasi untuk membaca line, blackberru, pesan, facebook",
       "spyware untuk hp android",  "spyware untuk perangkat android",
       "app, aplikasi untuk merekam pembicaraan telepon",
        "cara mengakses hp jarak jau",
    ],
    # German Germany
    'de_de': [
        "Wie fange ich meine betrügerische {agent} App?",
        "Wie verfolge ich meine betrügerische {agent} App",
        "App zum Ausspionieren meines {agent}",
        "App zum Verfolgen meines {agent}",
        "Standort einer anderen Telefon-App abrufen",
        "Anrufe von einer anderen Geräte-App abhören",
        "Verfolge meinen {agent}",
        "Verfolge das Telefon meines {agent}, ohne dass sie es wissen",
        "Verfolge den Standort meiner {agent} App",
        "Lesen Sie eine SMS von einer anderen Telefon-App",
        "App zum Verfolgen meiner Kinder",
        "App für meine Kinder Telefon zu sehen",
        "Keylogger für Android",
        "einfache Spionage-App für Android",
        "versteckte Spionage-App für Android",
        "App, um Fotos in meinem Telefon aus der Ferne zu sehen",
        "Alle WhatsApp Nachrichten App anzeigen",
        "Alle Facebook-Nachrichten-App anzeigen",
        "Spyware für Android-Geräte",
        "App aufzeichnen",
    ],
}


def seed_queries(store, LANG=LANG, COUNTRY=COUNTRY):
    code = '{}_{}'.format(LANG, COUNTRY)
    qs = []
    if store in ('android', 'ios'):
        qs = PLAYSTORE_STARTING_QUERIES[code]
    elif store.startswith('google'):
        qs = GOOGLE_STARTING_QUERY[code]
    else:
        qs = []

    return set(q.format(agent=agent) for agent in AGENT[code]
               for q in qs)
